spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_second_level_cache: true
  datasource:
    url: jdbc:h2:mem:test;MODE=DB2;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: db/db.changelog-master.xml

logging:
  level:
    org.hibernate.SQL: debug
    root: INFO